// 预加载: 安全暴露后端 API 给渲染进程
const { contextBridge, ipcRenderer, on } = require("electron");
contextBridge.exposeInMainWorld("api", {
  getSettings: () => ipcRenderer.invoke("get-settings"),
  saveSettings: (patch) => ipcRenderer.invoke("save-settings", patch),
  resetSettings: () => ipcRenderer.invoke("reset-settings"),
  getStatus: () => ipcRenderer.invoke("get-status"),
  getQuickStatus: () => ipcRenderer.invoke("get-quick-status"),
  gatewayAction: (a) => ipcRenderer.invoke("gateway-action", a),
  doctor: () => ipcRenderer.invoke("doctor"),
  killProcesses: () => ipcRenderer.invoke("kill-processes"),
  openPath: (w) => ipcRenderer.invoke("open-path", w),
  copyText: (t) => ipcRenderer.invoke("copy-text", t),
  getHistory: () => ipcRenderer.invoke("get-history"),
  clearHistory: () => ipcRenderer.invoke("clear-history"),
  deleteHistory: (i) => ipcRenderer.invoke("delete-history", i),
  exportHistoryCSV: () => ipcRenderer.invoke("export-history-csv"),
  startUpdate: () => ipcRenderer.invoke("start-update"),
  cancelUpdate: () => ipcRenderer.invoke("cancel-update"),
  maintain: () => ipcRenderer.invoke("maintain"),
  onMaintainLine: (fn) => ipcRenderer.on("maintain-line", (e, d) => fn(d)),
  onMaintainDone: (fn) => ipcRenderer.on("maintain-done", (e, d) => fn(d)),
  getLogs: () => ipcRenderer.invoke("get-logs"),
  clearLogFile: () => ipcRenderer.invoke("clear-log-file"),
  restoreZhPatches: () => ipcRenderer.invoke("restore-zh-patches"),
  recentCommits: () => ipcRenderer.invoke("recent-commits"),
  rollback: (c) => ipcRenderer.invoke("rollback", c),
  setLoginItem: (en) => ipcRenderer.invoke("set-login-item", en),
  netProbe: () => ipcRenderer.invoke("net-probe"),
  exportSettings: () => ipcRenderer.invoke("export-settings"),
  importSettings: () => ipcRenderer.invoke("import-settings"),
  exportText: (name, content) => ipcRenderer.invoke("export-text", { name, content }),
  exportData: () => ipcRenderer.invoke("export-data"),
  importData: () => ipcRenderer.invoke("import-data"),
  windowControl: (c) => ipcRenderer.invoke("window-control", c),
  getNotifications: () => ipcRenderer.invoke("get-notifications"),
  clearNotifications: () => ipcRenderer.invoke("clear-notifications"),
  markNotificationsRead: () => ipcRenderer.invoke("mark-notifications-read"),
  openReleases: () => ipcRenderer.invoke("open-releases"),
  saveProfile: (name) => ipcRenderer.invoke("save-profile", name),
  applyProfile: (name) => ipcRenderer.invoke("apply-profile", name),
  deleteProfile: (name) => ipcRenderer.invoke("delete-profile", name),
  getAppInfo: () => ipcRenderer.invoke("get-app-info"),
  repoStatus: () => ipcRenderer.invoke("repo-status"),
  checkoutBranch: () => ipcRenderer.invoke("checkout-branch"),
  repairDeps: () => ipcRenderer.invoke("repair-deps"),
  translateLines: (lines) => ipcRenderer.invoke("translate-lines", lines),
  onRepairLine: (fn) => ipcRenderer.on("repair-line", (e, d) => fn(d)),
  onRepairDone: (fn) => ipcRenderer.on("repair-done", (e, d) => fn(d)),
  onNotification: (fn) => ipcRenderer.on("notification", (e, d) => fn(d)),
  onUpdateStarted: (fn) => ipcRenderer.on("update-started", (e, d) => fn(d)),
  onUpdateLine: (fn) => ipcRenderer.on("update-line", (e, d) => fn(d)),
  onUpdateDone: (fn) => ipcRenderer.on("update-done", (e, d) => fn(d)),
  onNav: (fn) => ipcRenderer.on("nav", (e, d) => fn(d)),
  onDoCheck: (fn) => ipcRenderer.on("do-check", (e) => fn()),
  // 安装路径自动识别
  detectInstallPaths: (deep) => ipcRenderer.invoke("detect-install-paths", deep),
  checkInstallPath: (p) => ipcRenderer.invoke("check-install-path", p),
  browseInstallPath: () => ipcRenderer.invoke("browse-install-path"),
  onSettingsUpdated: (fn) => ipcRenderer.on("settings-updated", (e, d) => fn(d)),
  // 更新前预检
  preflightCheck: () => ipcRenderer.invoke("preflight-check"),
  // 已知安装管理 + 诊断报告
  addKnownInstall: (p) => ipcRenderer.invoke("add-known-install", p),
  removeKnownInstall: (p) => ipcRenderer.invoke("remove-known-install", p),
  exportDiagReport: () => ipcRenderer.invoke("export-diag-report"),
  // 连通性测试
  testConnection: () => ipcRenderer.invoke("test-connection"),
  speedTest: () => ipcRenderer.invoke("speedtest"),
  applyNetMethod: (key) => ipcRenderer.invoke("apply-net-method", key),
  snooze: (hours) => ipcRenderer.invoke("snooze", hours),
  getSnooze: () => ipcRenderer.invoke("get-snooze"),
  onAutoCountdown: (cb) => ipcRenderer.on("auto-countdown", (e, d) => cb(d)),
  countdownAction: (action) => ipcRenderer.invoke("countdown-action", action),
  exportHealthReport: () => ipcRenderer.invoke("export-health-report"),
  dirSize: () => ipcRenderer.invoke("dir-size"),
  getConnTests: () => ipcRenderer.invoke("get-conn-tests"),
  restoreLatestBackup: () => ipcRenderer.invoke("restore-latest-backup"),
  envInfo: () => ipcRenderer.invoke("env-info"),
  installPreflight: (dir) => ipcRenderer.invoke("install-preflight", dir),
  getInstallVersions: () => ipcRenderer.invoke("get-install-versions"),
  startInstall: (opts) => ipcRenderer.invoke("start-install", opts),
  cancelInstall: () => ipcRenderer.invoke("cancel-install"),
  uninstallPreflight: (dir) => ipcRenderer.invoke("uninstall-preflight", dir),
  backupInstallConfig: (dir) => ipcRenderer.invoke("backup-install-config", dir),
  uninstallHermes: (dir, mode, opts) => ipcRenderer.invoke("uninstall-hermes", { dir, mode, opts }),
  getInstallHistory: () => ipcRenderer.invoke("get-install-history"),
  listBackups: () => ipcRenderer.invoke("list-backups"),
  restoreBackup: (name) => ipcRenderer.invoke("restore-backup", name),
  // 备份与恢复 (Hermes 配置/会话/技能/插件/数据)
  bkScopes: () => ipcRenderer.invoke("bk-scopes"),
  bkList: () => ipcRenderer.invoke("bk-list"),
  bkBackupNow: (payload) => ipcRenderer.invoke("bk-backup-now", payload),
  bkRestore: (name) => ipcRenderer.invoke("bk-restore", name),
  bkDelete: (name) => ipcRenderer.invoke("bk-delete", name),
  bkExport: (payload) => ipcRenderer.invoke("bk-export", payload),
  bkOpenDir: () => ipcRenderer.invoke("bk-open-dir"),
  bkPrune: () => ipcRenderer.invoke("bk-prune"),
  bkVerify: (name) => ipcRenderer.invoke("bk-verify", name),

  // 国内 Electron 镜像 (em)
  emPresets: () => ipcRenderer.invoke("em-presets"),
  emGroups: () => ipcRenderer.invoke("em-groups"),
  emDetect: () => ipcRenderer.invoke("em-detect"),
  emSetSite: (payload) => ipcRenderer.invoke("em-set-site", payload),
  emEnvPreview: () => ipcRenderer.invoke("em-env-preview"),
  emResolved: () => ipcRenderer.invoke("em-resolved"),
  emProbe: () => ipcRenderer.invoke("em-probe"),
  emApplyProbe: () => ipcRenderer.invoke("em-apply-probe"),
  emNpmrc: (enable) => ipcRenderer.invoke("em-npmrc", enable),
  emNpmrcPath: () => ipcRenderer.invoke("em-npmrc-path"),
  cleanupScan: () => ipcRenderer.invoke("cleanup-scan"),
  cleanupRun: (keys) => ipcRenderer.invoke("cleanup-run", keys),
  whatsNew: () => ipcRenderer.invoke("whats-new"),
  changelogFetch: () => ipcRenderer.invoke("changelog-fetch"),
  updateTargets: () => ipcRenderer.invoke("update-targets"),
  setUpdateTarget: (target) => ipcRenderer.invoke("set-update-target", target),
  webhookTest: () => ipcRenderer.invoke("webhook-test"),
  hooksSave: (hooks) => ipcRenderer.invoke("hooks-save", hooks),
  hooksGet: () => ipcRenderer.invoke("hooks-get"),
  installMirrorTest: () => ipcRenderer.invoke("install-mirror-test"),
  procList: () => ipcRenderer.invoke("proc-list"),
  procKill: (pid) => ipcRenderer.invoke("proc-kill", pid),
  updateStats: () => ipcRenderer.invoke("update-stats"),
  onCleanupLine: (cb) => ipcRenderer.on("cleanup-line", (e, l) => cb(l)),
  onInstallLine: (cb) => ipcRenderer.on("install-line", (e, l) => cb(l)),
  onInstallStage: (cb) => ipcRenderer.on("install-stage", (e, d) => cb(d)),
  onInstallDone: (cb) => ipcRenderer.on("install-done", (e, d) => cb(d)),
  onInstallHistoryUpdated: (cb) => ipcRenderer.on("install-history-updated", () => cb()),
});
